---
- name: Disable apache service
  service:
    name: apache2
    state: stopped
    enabled: no
- name: Remove apache
  package:
    name: apache2
    state: absent
- name: Install nginx
  package:
    name: nginx
    state: present
- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
- name: Remove the default nginx sites-enabled
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
- name: Remove the default nginx sites-available
  file:
    name: /etc/nginx/sites-available/default
    state: absent
  notify:
    - restart nginx
- name: Generate a new sites-available for Drupal
  template:
    src: drupal.conf
    dest: /etc/nginx/sites-available/drupal.conf
    owner: www-data
    group: www-data
- name: Link sites-enabled
  file:
    src: /etc/nginx/sites-available/drupal.conf
    dest: /etc/nginx/sites-enabled/drupal.conf
    state: link
  notify:
    - restart nginx
- name: Flush handlers
  meta: flush_handlers