---
- hosts: localhost
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefixes: "172.17.0.0/16"
    - name: Add vmss subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_subnet_name }}"
        address_prefix: "172.17.0.0/24"
        virtual_network: "{{ vnet_name }}"
    - name: Add glusterfs subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ gfs_subnet_name }}"
        address_prefix: "172.17.1.0/24"
        virtual_network: "{{ vnet_name }}"
